#ifndef STARBURST_SLEEPMASK_VS_DATA_H
#define STARBURST_SLEEPMASK_VS_DATA_H

/*
 * Sleepmask-VS embedded COFF data.
 *
 * This file is auto-generated by builder.py when sleep_mask=sleepmask_vs.
 * It contains the compiled sleepmask .o file as a byte array.
 *
 * To generate manually for local builds:
 *   1. Compile sleepmask-vs in Visual Studio (Release x64)
 *   2. Run: python3 scripts/embed_sleepmask.py path/to/default-sleepmask.x64.o
 *
 * The placeholder below will cause a build error if selected without
 * providing the actual sleepmask data.
 */

#ifndef SLEEPMASK_VS_COFF_DATA_DEFINED

static const uint8_t SLEEPMASK_VS_COFF[] = { 0 };
static const uint32_t SLEEPMASK_VS_COFF_SIZE = 0;

#endif

#endif
